### ISSUE TITLE
Opponents' stats cannot be browsed anymore (F8 key)

### ISSUE THREAD

**Issue by troussis** [Deaod/UTComp#1]
@Deaod

**Comment by Deaod** [comment]
Looks like UTComp_Scoreboard is missing implementation for NextStats

**Comment by Deaod** [comment]
Actually, it seems that entire feature was lost due to this version being based on 1.7 beta4, and not the release version 1.7a. I dont think its terribly hard to put back in, but its a lot of code to look through.

**Comment by Deaod** [comment]
Fixed with 1.8a
