### ISSUE TITLE
minimegatex.utx is required in server's or client's textures folder for the mutator to work

### ISSUE THREAD

**Issue by troussis** [Deaod/UTComp#2]

**Comment by troussis** [comment]
@Deaod

**Comment by Deaod** [comment]
This either requires a different build process or some other trick that i dont know how to perform.

**Comment by Deaod** [comment]
I think i managed to remove the dependency, unfortunately it required a manual edit to StaticMesh'UTCompv18a.MiniSuperHealth' (changing Materials[0].Material to FinalBlend'UTCompv18a.minimegatex').

EDIT: Confirmed working now. Ill adapt the release process, but wont bother doing this for development versions.

**Comment by Deaod** [comment]
Fixed with 1.8a
